[[bin]]
name = "migrate-setup"
path = "src/bin/migrate_setup.rs"

[[bin]]
name = "migrate-up"
path = "src/bin/migrate_up.rs"

[[bin]]
name = "migrate-down"
path = "src/bin/migrate_down.rs"

[[bin]]
name = "migrate-create"
path = "src/bin/migrate_create.rs"
